### ISSUE TITLE
PREFACIO

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#10]

**Comment by gamontec** [comment]
Párrafo #2 

_"Por ejemplo, la mayoría de nosotros sabe que rotando una perilla de volumen en el sentido del **relok**, el sonido emanando del amplificador aumentará su volumen."_

**Comment by gamontec** [comment]
Párrafo Nº6

_"Espero que aproveches los excelentes ejemplos en Max que los autores han creado. Son **simultaneamente** entretenidos y esclarecedores, y suenan lo suficientemente bien como para ser usados en el escenario."_

- "simultáneamente"

**Comment by gamontec** [comment]
Prefacio **Revisado**!

**Comment by aamontoya89** [comment]
corregido
