### ISSUE TITLE
1T

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#11]

**Comment by gamontec** [comment]
1.1 SÍNTESIS DE SONIDO Y PROCESAMIENTO DE SEÑALES

Párrafo Nº 2

_"Lo mismo ha pasado en la animación gráfica: gracias al computador ahora es posible crear imágenes y secuencias de películas extremadamente **realísticas**..."_

- "extremadamente reales"

**Comment by gamontec** [comment]
1.1 SÍNTESIS DE SONIDO Y PROCESAMIENTO DE SEÑALES

Párrafo Nº 3

"Estas posibilidades nuevas son el resultado de pasar del **munod** análogo al digital."

**Comment by gamontec** [comment]
1.1 SÍNTESIS DE SONIDO Y PROCESAMIENTO DE SEÑALES

Párrafo Nº4

"Este texto se concentrará en dos temas: síntesis de sonido y procesamiento de señales.

Síntesis de sonido significa la generación electrónica de **sonida**. En la práctica, encontrarás que las posibilidades de creación de **sonida** están basadas mayormente"

**Comment by gamontec** [comment]
1.1 SÍNTESIS DE SONIDO Y PROCESAMIENTO DE SEÑALES

SÍNTESIS DIGITAL DE SONIDO

_"La interfaz de audio, en otras palabras, convierte los datos digitales en un **voltage** análogo"_

- En español es **voltaje**

**Comment by gamontec** [comment]
1.1 SÍNTESIS DE SONIDO Y PROCESAMIENTO DE SEÑALES

PROCESAMIENTO DE SEÑALES

Sonido pre-grabado, el cual es luego procesado en tiempo real.

_"El **programa. aunque** está procesando en tiempo real, también puede grabar el flujo resultante en un archivo de audio para su posterior escucha, como en la Fig. 1.4."_

- Hay un "." en vez de una ","

**Comment by aamontoya89** [comment]
corregido
