### ISSUE TITLE
Párrafo "Prerequisitos"

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#2]
_"Los capítulos teóricos no son **substituto** de textos más profundos sobre síntesis**, sino que proveen con un esquema orgánico para aprender** la teoría necesaria para crear sonidos en el computador y escribir programas de procesamiento de señales. **En adición** a tu iPad, también necesitarás un computador para las secciones prácticas."_

- "Substituto" suena a una traducción literal desde el inglés. Si bien se usa, es más común usar "Sustituto"
- Sobra un "con" en "sino que proveen con un esquema orgánico"
- "En adición" suena también a traducción literal del inglés. Usar "Adicional a" u otra fórmula.

**Comment by aamontoya89** [comment]
corregido
