### ISSUE TITLE
"TEORÍA y PRÁCTICA"

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#4]

**Comment by gamontec** [comment]
_"y aquellos entusiastas, **muchos más numerosos**, que aman inventar y modificar sonidos usando su computador."_
- "mucho más numerosos" en vez de "muchos más numerosos"

**Comment by gamontec** [comment]
"Es nuestra intención ayudar a estos usuarios de software musical a adquirir un entendimiento más profundo **que los llevará más allá de los confines de algún software en específico y a acceder al inherente y profundo poder en el medio sonoro**."

- No queda claro lo que intenta decir la última frase.

**Comment by aamontoya89** [comment]
corregido
