### ISSUE TITLE
"MAX"

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#5]

**Comment by gamontec** [comment]
"Es usado a lo largo del mundo por músicos, compositores, diseñadores sonoros, artistas visuales y artistas multimedia, y se ha convertido en el estándar defacto para proyectos creativos modernos tecnológicos, tanto en las esferas musicales como visuales."

- "En todo el mundo" o "Alrededor del mundo" en vez de "A lo largo del mundo".
- No me suene el término "defacto" aplicado a este contexto. Sugiero dejar solamente "se ha convertido en el estándar para proyectos..."

**Comment by gamontec** [comment]
"En Max uno crea programas por medio de conectar objetos gráficos en la pantalla con cables virtuales."

- Sugiero usar "uno crea programas por medio de la conexión de objetos gráficos..."

**Comment by aamontoya89** [comment]
corregido
