### ISSUE TITLE
"ENFOQUE EDUCATIVO Y MÉTODO DE ESTE LIBRO"

### ISSUE THREAD

**Issue by gamontec** [aamontoya89/electronic_music_and_sound_design#6]

**Comment by gamontec** [comment]
_"Sobre la **baes** de los problemas y conceptos ya descritos,"_

**Comment by gamontec** [comment]
_"Los capítulos prácticos del libro también incluyen muchas otras características y actividades, incluyendo la corrección, **compleción**, implementación, corrección, prueba y análisis de algoritmos"_

- Buscar otro término que explique la idea.

**Comment by gamontec** [comment]
"Las actividades en este libro que se concentran en reemplazar partes de algoritmos, corregir algortimos defectuosos e **ingeniería en reversa**, han sido incluidos para proponer problemas..."

- Sugiero utilizar "corregir algoritmos defectuosos y la aplicación de ingeniería inversa..."

**Comment by gamontec** [comment]
_"En este contexto, es vitalmente importante que el estudiante trabaje en estas actividades para evitar una aproximación excesivamente **pasivo** al aprendizaje."_

- "pasiva"

**Comment by aamontoya89** [comment]
corregido
